using ProyectoAtlas.Domain.Features;

namespace ProyectoAtlas.Application.Features.FeatureDocumentationLinks.ListByFeature;

public record ListFeatureDocumentationLinksResponse(IReadOnlyCollection<FeatureDocumentationLink> Items);
