using ProyectoAtlas.Domain.Features;

namespace ProyectoAtlas.Application.Features.FeatureDocumentationLinks.ListByDocumentation;

public record ListDocumentationFeatureLinksResponse(IReadOnlyCollection<FeatureDocumentationLink> Items);
